name: CI-CD

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

  jobs:
    CI:
        runs-on: ubuntu-latest
        step:
            -run : echo "Obter o código 1"
            -run : echo "Enviar a imagem docker para o docker hub"

    CD:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Obter o código"
            - run: echo "Configurar o kubeconfig"
            - run: echo "Configurar o kubeconfig"
